### ISSUE TITLE
Super Large Data Sets

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#1733]
We need to test the performance against super large record sets. Probably should be a manual test, but we should check it.

**Comment by PMQABen** [comment]
Just to make sure, this is for the Record List control on Screens right?

```py
import json, names

names = []
for i in range(0,10000):
    array = {'value':names.get_first_name(),'content':names.get_last_name()}
    names.append(data)

print(json.dumps(names))
```
This'll dump 10k randomly generated names into JSON format. Obviously we can go higher than that, just gotta change the range on line 4. Just gotta run this, dump the output to a file somewhere, and then copy/paste it into a Record List.

**Comment by velkymx** [comment]
We should use the factories in Tinker to populate the database.

**Comment by PMQABen** [comment]
Soooo:

```php
<?php

use ProcessMaker\Models\User;
use ProcessMaker\Models\Group;
use ProcessMaker\Models\ProcessCategory;
use ProcessMaker\Models\Screen;
use ProcessMaker\Models\Script;
use ProcessMaker\Models\EnvironmentVariable;
use ProcessMaker\Models\ProcessWebhook;
use ProcessMaker\Models\Process;
use ProcessMaker\Models\ProcessRequestToken;

factory(User::class, 1000000)->create();
factory(ProcessCategory::class, 1000000)->create();
factory(Group::class, 1000000)->create();
factory(Screen::class, 1000000)->create();
factory(Script::class, 1000000)->create();
factory(EnvironmentVariable::class, 1000000)->create();
factory(ProcessWebhook::class, 1000000)->create();
factory(Process::class, 1000000)->create();
factory(ProcessRequestToken::class, 1000000)->create();
```
![image](https://user-images.githubusercontent.com/28575916/56600288-31c12580-65ad-11e9-8ec6-a04ebada966f.png)

**Comment by PMQABen** [comment]
One thing I'm noticing is the `User::` command starts running into duplicate key entries pretty quickly, it's tough to get higher than 5000-7000 users.

```
/admin/users
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) in /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 389
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /home/vagrant/processmaker/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 158

mysql> select count(*) from groups;
+----------+
| count(*) |
+----------+
|  1673587 |
+----------+

mysql> select count(*) from users;
+----------+
| count(*) |
+----------+
|     7086 |
+----------+
```

**Comment by PMQABen** [comment]
New issue.

Using Factory/Tinker to add in 100,000 Process Categories, and when loading the `/processes` page, the page takes a long time to load, CPU time pegs at 100%+, and the memory usage balloons. At one point what should have been a sub 100mb page size increased to 700mb.

Trying to create a process in this sort of state is _**excruciatingly**_ slow, and can make the user believe their browser has locked up.

**Comment by PMQABen** [comment]
More errors. Used php artisan tinker to create 110,000 processes, using the same category and user:
```
[2019-05-13 18:06:23] testing.ERROR: Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) {"userId":1,"email":"morgan.turcotte@hotmail.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) at /home/vagrant/processmaker/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)
[stacktrace]
#0 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(137): Symfony\\Component\\Debug\\Exception\\FatalErrorException->__construct()
#1 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->fatalExceptionFromError()
#2 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()
#3 /home/vagrant/processmaker/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): Doctrine\\DBAL\\Driver\\PDOStatement->execute()
#4 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Database/Connection.php(330): Doctrine\\DBAL\\Driver\\PDOStatement->execute()
#5 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\\Database\\MySqlConnection->Illuminate\\Database\\{closure}()
#6 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\MySqlConnection->runQueryCallback()
#7 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\MySqlConnection->run()
#8 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2095): Illuminate\\Database\\MySqlConnection->select()
#9 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2083): Illuminate\\Database\\Query\\Builder->runSelect()
#10 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2569): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#11 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2084): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#12 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(519): Illuminate\\Database\\Query\\Builder->get()
#13 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(503): Illuminate\\Database\\Eloquent\\Builder->getModels()
#14 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(461): Illuminate\\Database\\Eloquent\\Builder->get()
#15 /home/vagrant/processmaker/ProcessMaker/Http/Controllers/ProcessController.php(37): Illuminate\\Database\\Eloquent\\Model::all()
#16 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): ProcessMaker\\Http\\Controllers\\ProcessController->index()
#17 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array:{/home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54}()
#18 /home/vagrant/processmaker/ProcessMaker/Http/Controllers/Controller.php(35): ProcessMaker\\Http\\Controllers\\ProcessController->callAction()
#19 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): ProcessMaker\\Http\\Controllers\\ProcessController->callAction()
#20 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#21 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#22 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Routing\\Route->run()
#23 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#24 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#25 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): ProcessMaker\\Http\\Middleware\\SanitizeInput->handle()
#26 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/vagrant/processmaker/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#28 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()
#29 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /home/vagrant/processmaker/ProcessMaker/Http/Middleware/GenerateMenus.php(205): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#31 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): ProcessMaker\\Http\\Middleware\\GenerateMenus->handle()
#32 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#34 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#35 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#37 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#38 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/vagrant/processmaker/ProcessMaker/Http/Middleware/SetLocale.php(34): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#40 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): ProcessMaker\\Http\\Middleware\\SetLocale->handle()
#41 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#43 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#44 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /home/vagrant/processmaker/ProcessMaker/Http/Middleware/SessionStarted.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#46 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): ProcessMaker\\Http\\Middleware\\SessionStarted->handle()
#47 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#49 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle()
#50 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#52 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#53 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#55 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): ProcessMaker\\Http\\Middleware\\EncryptCookies->handle()
#56 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#58 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Routing\\Pipeline->then()
#59 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack()
#60 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute()
#61 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute()
#62 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch()
#63 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): ProcessMaker\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#64 /home/vagrant/processmaker/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#65 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): ProcessMaker\\Http\\Middleware\\TrustProxies->handle()
#66 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#68 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#69 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#70 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#71 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): ProcessMaker\\Http\\Middleware\\TrimStrings->handle()
#72 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#73 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#74 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#75 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#76 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#77 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#78 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#79 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#80 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Routing\\Pipeline->then()
#81 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): ProcessMaker\\Http\\Kernel->sendRequestThroughRouter()
#82 /home/vagrant/processmaker/public/index.php(11): ProcessMaker\\Http\\Kernel->handle()
#83 /home/vagrant/processmaker/public/index.php(0): {main}()
#84 {main}
"} 
```

**Comment by velkymx** [comment]
Diabolical. We've integrated this into the upcoming stress testing suite
