### ISSUE TITLE
Customize UI NPM Error

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2225]
ERROR  Failed to compile with 2 errors                                                                                                      4:59:20 PM
​
 error  in ./resources/sass/app.scss
​
Module build failed:
@import '../../public/css/precompiled/bootstrap/bootstrap.scss';
^
      File to import not found or unreadable: ../../public/css/precompiled/bootstrap/bootstrap.scss.
      in /root/processmaker-develop/resources/sass/app.scss (line 7, column 1)
​
 @ ./resources/sass/app.scss 4:14-254
 @ multi ./resources/js/app-layout.js ./resources/sass/sidebar/sidebar.scss ./resources/sass/app.scss ./resources/sass/admin/queues.scss
​
 error  in ./resources/sass/app.scss
​
Module build failed: ModuleBuildError: Module build failed:
@import '../../public/css/precompiled/bootstrap/bootstrap.scss';
^
      File to import not found or unreadable: ../../public/css/precompiled/bootstrap/bootstrap.scss.
      in /root/processmaker-develop/resources/sass/app.scss (line 7, column 1)
    at /root/processmaker-develop/node_modules/webpack/lib/NormalModule.js:195:19
    at /root/processmaker-develop/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /root/processmaker-develop/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/root/processmaker-develop/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.callback (/root/processmaker-develop/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.done [as callback] (/root/processmaker-develop/node_modules/neo-async/async.js:8067:18)
    at options.error (/root/processmaker-develop/node_modules/node-sass/lib/index.js:294:32)

**Comment by danloa** [comment]
The error is caused when running npm install as root. We added instruction to create directories and copy files that can be run as root. Run

npm install --unsafe-perm=true

when logged as root
