### ISSUE TITLE
Timer Events Hanging

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2825]
We were seeing issues with a PM4 GA build where you were no login able to login. Going to the login page would just show a white screen. The following error was seen in ProcessMaker Logs

```
[2020-02-04 19:17:44] production.ERROR: Call to a member function getKey() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getKey() on null at /opt/processmaker/ProcessMaker/Repositories/ExecutionInstanceRepository.php:108)
[stacktrace]
#0 /opt/processmaker/vendor/processmaker/nayra/src/ProcessMaker/Nayra/Engine/EngineTrait.php(143): ProcessMaker\\Repositories\\ExecutionInstanceRepository->persistInstanceCreated(Object(ProcessMaker\\Models\\ProcessRequest))
#1 /opt/processmaker/ProcessMaker/Jobs/StartEvent.php(39): ProcessMaker\\BpmnEngine->createExecutionInstance(Object(ProcessMaker\\Nayra\\Bpmn\\Models\\Process), Object(ProcessMaker\\Models\\DataStore))
#2 [internal function]: ProcessMaker\\Jobs\\StartEvent->action(Object(ProcessMaker\\Nayra\\Bpmn\\Models\\Process), Object(ProcessMaker\\Nayra\\Bpmn\\Models\\StartEvent), Object(ProcessMaker\\Nayra\\Storage\\BpmnDocument), NULL, NULL, Array, Object(ProcessMaker\\Models\\Process))
#3 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#4 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(ProcessMaker\\Application), Array, Object(Closure))
#6 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(ProcessMaker\\Application), Array, Array, NULL)
#7 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(239): Illuminate\\Container\\Container->call(Array, Array)
#8 /opt/processmaker/ProcessMaker/Jobs/BpmnAction.php(74): Illuminate\\Support\\Facades\\Facade::__callStatic('call', Array)
#9 [internal function]: ProcessMaker\\Jobs\\BpmnAction->handle()
#10 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#11 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(ProcessMaker\\Application), Array, Object(Closure))
#13 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(ProcessMaker\\Application), Array, Array, NULL)
#14 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#15 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(ProcessMaker\\Jobs\\StartEvent))
#16 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(ProcessMaker\\Jobs\\StartEvent))
#17 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#18 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(26): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(ProcessMaker\\Jobs\\StartEvent))
#19 /opt/processmaker/ProcessMaker/Managers/WorkflowManager.php(115): ProcessMaker\\Jobs\\BpmnAction::dispatchNow(Object(ProcessMaker\\Models\\Process), Object(ProcessMaker\\Nayra\\Bpmn\\Models\\StartEvent), Array)
#20 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(239): ProcessMaker\\Managers\\WorkflowManager->triggerStartEvent(Object(ProcessMaker\\Models\\Process), Object(ProcessMaker\\Nayra\\Bpmn\\Models\\StartEvent), Array)
#21 /opt/processmaker/ProcessMaker/Managers/TaskSchedulerManager.php(238): Illuminate\\Support\\Facades\\Facade::__callStatic('triggerStartEve...', Array)
#22 /opt/processmaker/ProcessMaker/Managers/TaskSchedulerManager.php(157): ProcessMaker\\Managers\\TaskSchedulerManager->executeTimerStartEvent(Object(ProcessMaker\\Models\\ScheduledTask), Object(stdClass))
#23 /opt/processmaker/ProcessMaker/Console/Kernel.php(36): ProcessMaker\\Managers\\TaskSchedulerManager->scheduleTasks(Object(Illuminate\\Console\\Scheduling\\Schedule))
#24 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(108): ProcessMaker\\Console\\Kernel->schedule(Object(Illuminate\\Console\\Scheduling\\Schedule))
#25 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(90): Illuminate\\Foundation\\Console\\Kernel->defineConsoleSchedule()
#26 [internal function]: Illuminate\\Foundation\\Console\\Kernel->Illuminate\\Foundation\\Console\\{closure}(Object(ProcessMaker\\Application))
#27 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(866): call_user_func(Object(Closure), Object(ProcessMaker\\Application))
#28 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(815): Illuminate\\Foundation\\Application->fireAppCallbacks(Array)
#29 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#30 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(210): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(ProcessMaker\\Application))
#31 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(322): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#32 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#33 /opt/processmaker/artisan(30): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 {main}
```

When attempting to restart horizon on the server, the error would show up in command line:

This is the second time we've seen the app go down due to issues with timer_events and processes. In order to fix, we set pause_timer_start=1 in the process table for id=5. As soon as the change was made, horizon was able to start up properly and the UI was working again.

Could you please look into the process and database and see why this single process was breaking the whole instance? It would be nice if the failure was more graceful so the application was still usable.

Let me know if you need any additional information from my side.

**Comment by caleeli** [comment]
Could you give us the url and credentials to see the process 5 or and exported file of it.

**Comment by caleeli** [comment]
Could you help us to find an error message in any of the log files, that has a reference to this file:
**ProcessMaker/Traits/HasVersioning.php**
or this class:
**ProcessMaker\Traits\HasVersioning**
