### ISSUE TITLE
Test Send Email package v1.1.9

### ISSUE THREAD

**Issue by PMQABen** [ProcessMaker/processmaker#3043]
https://github.com/ProcessMaker/connector-send-email/releases/tag/v1.1.9

**Comment by PMQABen** [comment]
Trying to send an email screen via a basic send email control process:
```
[2020-04-11 00:14:42] production.ERROR: 1 {"exception":"[object] (Exception(code: 0): 1 at /home/vagrant/processmaker-plugins/connector-send-email/src/ScreenRenderer.php:19)
[stacktrace]
#0 /home/vagrant/processmaker-plugins/connector-send-email/src/Controllers/EmailController.php(75): ProcessMaker\\Packages\\Connectors\\Email\\ScreenRenderer::render(Array, Array)
#1 [internal function]: ProcessMaker\\Packages\\Connectors\\Email\\Controllers\\EmailController->send(Object(Illuminate\\Http\\Request))
#2 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#3 /home/vagrant/processmaker/ProcessMaker/Http/Controllers/Controller.php(36): Illuminate\\Routing\\Controller->callAction('send', Array)
#4 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): ProcessMaker\\Http\\Controllers\\Controller->callAction('send', Array)
#5 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(ProcessMaker\\Packages\\Connectors\\Email\\Controllers\\EmailController), 'send')
#6 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#7 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#8 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#11 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#12 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#13 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#14 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#15 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#16 /home/vagrant/processmaker/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#33 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#34 /home/vagrant/processmaker/public/index.php(11): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#35 {main}
"} 
[2020-04-11 00:14:43] production.ERROR: Script threw return code 255Message: 
Fatal error: Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST http://bpm4.local.processmaker.com/plugins/email/send` resulted in a `500 Internal Server Error` response:
<!DOCTYPE html><!--


Exception: 1 in file /home/vagrant/processmaker-plugins/connector-send-email/src/ScreenRenderer.ph (truncated...)
 in /opt/executor/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /opt/executor/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /opt/executor/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /opt/executor/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /opt/executor/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /opt/executor/ven in /opt/executor/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113  
[2020-04-11 00:14:43] production.INFO: Service task failed: connector-send-email/processmaker-communication-email-send - 
Fatal error: Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST http://bpm4.local.processmaker.com/plugins/email/send` resulted in a `500 Internal Server Error` response:
<!DOCTYPE html><!--


Exception: 1 in file /home/vagrant/processmaker-plugins/connector-send-email/src/ScreenRenderer.ph (truncated...)
 in /opt/executor/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /opt/executor/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /opt/executor/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /opt/executor/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /opt/executor/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /opt/executor/ven in /opt/executor/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113  
```
Mail never gets sent.

**Comment by PMQABen** [comment]
Version is now 1.1.10, but works as expected.
