### ISSUE TITLE
Importing Nested Forms in Pre 404 Screens

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3122]
We have the next issues:

1.- nested screen don't export or import is empty when you review the form
2.- display and email screens  don't export or import, is empty when you review the form

Export from 4.0.3 and import into 4.0.4

TODO: Test this scenario and document what the problem actually is before working on a fix.

**Comment by caleeli** [comment]
@velkymx The reason is because in 4.0.3 and before, the nested screens are not being exported and are not included in the exported file.
This functionality was added with this PR: https://github.com/ProcessMaker/processmaker/pull/2988

[Exporting Assets.4.0.3.json.txt](https://github.com/ProcessMaker/processmaker/files/4623259/Exporting.Assets.4.0.3.json.txt)
[Exporting.Assets.4.0.4.json.txt](https://github.com/ProcessMaker/processmaker/files/4623260/Exporting.Assets.4.0.4.json.txt)

**Comment by ZLTM** [comment]
Tested importing screens from https://processmaker.atlassian.net/browse/FOUR-1444
The screen 'listing review': 
https://www.dropbox.com/s/rudnqdh6miq4cbl/Listing%20Review%20Process%20%281%29.json?dl=0
won't upload, it shows the error message 'Unable to import the screen.'

**Comment by PMQABen** [comment]
![image](https://user-images.githubusercontent.com/28575916/82079368-9c9d3d00-9697-11ea-9402-520a650b7c9c.png)

It's throwing errors, but still appears to be importing
![image](https://user-images.githubusercontent.com/28575916/82079398-a6bf3b80-9697-11ea-9392-98e33c730ace.png)

**Comment by PMQABen** [comment]
Here's the main process file for this issue: [Listing Review Process.json.zip](https://github.com/ProcessMaker/processmaker/files/4636159/Listing.Review.Process.json.zip). When trying to import, it's throwing an "undefined offset" error:
```
[2020-05-15 17:47:28] production.ERROR: Undefined offset: 18 {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined offset: 18 at /home/vagrant/processmaker/ProcessMaker/Assets/ScreensInProcess.php:88)
[stacktrace]
#0 /home/vagrant/processmaker/ProcessMaker/Assets/ScreensInProcess.php(88): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined offse...', '/home/vagrant/p...', 88, Array)
#1 [internal function]: ProcessMaker\\Assets\\ScreensInProcess->updateReferences(Object(ProcessMaker\\Models\\Process), Array)
#2 /home/vagrant/processmaker/ProcessMaker/Managers/ExportManager.php(117): call_user_func(Array, Object(ProcessMaker\\Models\\Process), Array)
#3 /home/vagrant/processmaker/ProcessMaker/Managers/ExportManager.php(108): ProcessMaker\\Managers\\ExportManager->updateModelReferences(Object(ProcessMaker\\Models\\Process), Array)
#4 /home/vagrant/processmaker/ProcessMaker/Jobs/ImportProcess.php(646): ProcessMaker\\Managers\\ExportManager->updateReferences(Array)
#5 /home/vagrant/processmaker/ProcessMaker/Jobs/ImportProcess.php(678): ProcessMaker\\Jobs\\ImportProcess->saveBpmn(Object(stdClass))
#6 /home/vagrant/processmaker/ProcessMaker/Jobs/ImportProcess.php(716): ProcessMaker\\Jobs\\ImportProcess->parseFileV1()
#7 [internal function]: ProcessMaker\\Jobs\\ImportProcess->handle()
#8 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#9 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(ProcessMaker\\Application), Array, Object(Closure))
#11 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(ProcessMaker\\Application), Array, Array, NULL)
#12 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#13 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(ProcessMaker\\Jobs\\ImportProcess))
#14 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(ProcessMaker\\Jobs\\ImportProcess))
#15 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#16 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(26): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(ProcessMaker\\Jobs\\ImportProcess))
#17 /home/vagrant/processmaker/ProcessMaker/Http/Controllers/Api/ProcessController.php(720): ProcessMaker\\Jobs\\ImportProcess::dispatchNow('{\"type\":\"proces...')
#18 [internal function]: ProcessMaker\\Http\\Controllers\\Api\\ProcessController->import(Object(ProcessMaker\\Models\\Process), Object(Illuminate\\Http\\Request))
#19 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#20 /home/vagrant/processmaker/ProcessMaker/Http/Controllers/Controller.php(36): Illuminate\\Routing\\Controller->callAction('import', Array)
#21 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): ProcessMaker\\Http\\Controllers\\Controller->callAction('import', Array)
#22 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(ProcessMaker\\Http\\Controllers\\Api\\ProcessController), 'import')
#23 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#24 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#25 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Auth\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'import-processe...')
#28 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/vagrant/processmaker/ProcessMaker/Http/Middleware/SetLocale.php(34): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): ProcessMaker\\Http\\Middleware\\SetLocale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
#40 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#43 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#44 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#45 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#46 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#47 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#48 /home/vagrant/processmaker/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#58 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#61 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#64 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#65 /home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#66 /home/vagrant/processmaker/public/index.php(11): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#67 {main}
"} 
[2020-05-15 17:47:29] production.DEBUG: Javascript ProcessMaker.apiClient Error: {"message":"Request failed with status code 500","config":{"url":"/processes/import","method":"post","data":{},"headers":{"Accept":"application/json, text/plain, */*","X-Requested-With":"XMLHttpRequest","X-CSRF-TOKEN":"8euZSvWm0EYk0EDjQVnvkrX20kqdfmQOs4UAO7jk"},"baseURL":"/api/1.0/","transformRequest":[null],"transformResponse":[null],"timeout":30000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}  
```

**Comment by ZLTM** [comment]
Looks like it's an issue with the data connector using an invalid endpoint, here is a ticket explaining it
https://processmaker.atlassian.net/browse/FOUR-1479

**Comment by PMQABen** [comment]
Screens (form, nested, email, display) created in 4.0.3 import with no errors in 4.0.5, but during testing we found a problem with importing a 4.0.3 process. Since this ticket only involved screens, we will pass this through QA.
