### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by hmdshariati** [ProcessMaker/processmaker#3201]
error  in ./resources/sass/app.scss

Module build failed: 
@import '../../public/css/precompiled/bootstrap/bootstrap.scss';

version 4.0.5

**Comment by jemiris** [comment]
Hi @hmdshariati ,
could you please show the screenshot or explain the error briefly

**Comment by hegde89** [comment]
We have also facing the same error 

`> @processmaker/processmaker@4.0.13 development /home/azureuser/processmaker
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

98% after emitting SizeLimitsPlugin

 ERROR  Failed to compile with 2 errors                                                                                                        12:33:28 PM

 error  in ./resources/sass/app.scss

Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
7 │ @import '../../public/css/precompiled/bootstrap/bootstrap.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  /home/azureuser/processmaker/resources/sass/app.scss 7:9  root stylesheet
    at /home/azureuser/processmaker/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/azureuser/processmaker/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/azureuser/processmaker/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/azureuser/processmaker/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/azureuser/processmaker/node_modules/sass-loader/dist/index.js:73:7
    at Function.call$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:89862:16)
    at _render_closure1.call$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:79036:12)
    at _RootZone.runBinary$3$3 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:26612:18)
    at _FutureListener.handleError$1 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:25140:19)
    at _Future__propagateToListeners_handleError.call$0 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:25437:49)
    at Object._Future__propagateToListeners (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:4502:77)
    at _Future._completeError$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:25270:9)
    at _AsyncAwaitCompleter.completeError$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:24613:12)
    at Object._asyncRethrow (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:4251:17)
    at /home/azureuser/processmaker/node_modules/sass/sass.dart.js:13112:20
    at _wrapJsFunctionForAsync_closure.$protected (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:4276:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:24634:12)
    at _awaitOnObject_closure0.call$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:24626:25)
    at _RootZone.runBinary$3$3 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:26612:18)
    at _FutureListener.handleError$1 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:25140:19)
    at _Future__propagateToListeners_handleError.call$0 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:25437:49)
    at Object._Future__propagateToListeners (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:4502:77)
    at _Future._completeError$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:25270:9)
    at _AsyncAwaitCompleter.completeError$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:24613:12)
    at Object._asyncRethrow (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:4251:17)
    at /home/azureuser/processmaker/node_modules/sass/sass.dart.js:15754:20
    at _wrapJsFunctionForAsync_closure.$protected (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:4276:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:24634:12)
    at _awaitOnObject_closure0.call$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:24626:25)
    at _RootZone.runBinary$3$3 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:26612:18)
    at _FutureListener.handleError$1 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:25140:19)
    at _Future__propagateToListeners_handleError.call$0 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:25437:49)
    at Object._Future__propagateToListeners (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:4502:77)
    at _Future._completeError$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:25270:9)
    at _AsyncAwaitCompleter.completeError$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:24613:12)
    at Object._asyncRethrow (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:4251:17)

 error  in ./resources/sass/app.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
7 │ @import '../../public/css/precompiled/bootstrap/bootstrap.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  /home/azureuser/processmaker/resources/sass/app.scss 7:9  root stylesheet

 @ ./resources/sass/app.scss 2:14-253

                                                                        Asset       Size                                     Chunks             Chunk Names
                                                        /css/admin/queues.css    2.8 KiB                             /js/app-layout  [emitted]  /js/app-layout
                                                             /css/sidebar.css   1.17 KiB                             /js/app-layout  [emitted]  /js/app-layout
                                                /img/avatar-overlay-blank.png    2.2 KiB                                             [emitted]
                                                  /img/avatar-placeholder.gif   5.04 KiB                                             [emitted]
                                              /img/avatar-profile-overlay.png   3.24 KiB                                             [emitted]
                                                              /img/avatar.png    114 KiB                                             [emitted]
                                            /img/avatar_placeholder_small.png   13.1 KiB                                             [emitted]
                                                         /img/dottedArrow.png   35.5 KiB                                             [emitted]
                                                             /img/favicon.ico   1.12 KiB                                             [emitted]
                                                           /img/gears-big.png   12.7 KiB                                             [emitted]
                                                        /img/gears-big@2x.png   35.8 KiB                                             [emitted]
                                                        /img/gears-big@3x.png   64.7 KiB                                             [emitted]
                                                               /img/gears.png   18.9 KiB                                             [emitted]
                                                         /img/icon-pmlogo.png   2.11 KiB                                             [emitted]
                                                         /img/lg-blk-logo.png   12.6 KiB                                             [emitted]
                                                        /img/lg-blue-logo.png   13.6 KiB                                             [emitted]
                                                             /img/lg-icon.png    3.2 KiB                                             [emitted]
                                                         /img/lg-wht-logo.png   9.26 KiB                                             [emitted]
                                                                /img/logo.png   42.7 KiB                                             [emitted]
                                                         /img/md-blk-logo.png   7.73 KiB                                             [emitted]
                                                             /img/md-icon.png   2.07 KiB                                             [emitted]
                                                         /img/md-wht-logo.png   5.52 KiB                                             [emitted]
                                          /img/processmaker-icon-white-sm.png  683 bytes                                             [emitted]
                                             /img/processmaker-login-logo.png   4.54 KiB                                             [emitted]
                                      /img/processmaker_fulllogo_white-md.png   5.52 KiB                                             [emitted]
                                                   /img/processmaker_icon.png   1.45 KiB                                             [emitted]
                                                  /img/processmaker_login.png   8.39 KiB                                             [emitted]
                                                   /img/processmaker_logo.png   3.87 KiB                                             [emitted]
                                             /img/processmaker_logo_white.jpg   18.1 KiB                                             [emitted]
                                                               /img/robot.png   12.4 KiB                                             [emitted]
                                                         /img/sm-blk-logo.png   3.38 KiB                                             [emitted]
                                                        /img/sm-blue-logo.png   3.74 KiB                                             [emitted]
                                                             /img/sm-icon.png   1.05 KiB                                             [emitted]
                                                         /img/sm-wht-icon.png   3.34 KiB                                             [emitted]
                                                         /img/sm-wht-logo.png   2.27 KiB                                             [emitted]
                                                        /img/systemAvatar.png   2.72 KiB                                             [emitted]
                                                        /js/CustomActions.vue  958 bytes                                             [emitted]
                                                            /js/DetailRow.vue  875 bytes                                             [emitted]
                                                            /js/FilterBar.vue  628 bytes                                             [emitted]
                                              /js/admin/auth-clients/index.js    265 KiB               /js/admin/auth-clients/index  [emitted]  /js/admin/auth-clients/index
                                                /js/admin/cssOverride/edit.js    112 KiB                 /js/admin/cssOverride/edit  [emitted]  /js/admin/cssOverride/edit
                                                     /js/admin/groups/edit.js    236 KiB                      /js/admin/groups/edit  [emitted]  /js/admin/groups/edit
                                                    /js/admin/groups/index.js    265 KiB                     /js/admin/groups/index  [emitted]  /js/admin/groups/index
                                                    /js/admin/profile/edit.js    830 KiB                     /js/admin/profile/edit  [emitted]  /js/admin/profile/edit
                                          /js/admin/script-executors/index.js    271 KiB           /js/admin/script-executors/index  [emitted]  /js/admin/script-executors/index
                                                      /js/admin/users/edit.js   1.07 MiB                       /js/admin/users/edit  [emitted]  /js/admin/users/edit
                                                     /js/admin/users/index.js   1.09 MiB                      /js/admin/users/index  [emitted]  /js/admin/users/index
                                                            /js/app-layout.js   1.71 MiB                             /js/app-layout  [emitted]  /js/app-layout
                                                                   /js/app.js   10.8 MiB                                    /js/app  [emitted]  /js/app
                                                         /js/leave-warning.js   1.66 KiB                          /js/leave-warning  [emitted]  /js/leave-warning
                                                              /js/manifest.js   6.12 KiB                               /js/manifest  [emitted]  /js/manifest
                                                   /js/notifications/index.js    965 KiB                    /js/notifications/index  [emitted]  /js/notifications/index
                                                    /js/processes/archived.js    279 KiB                     /js/processes/archived  [emitted]  /js/processes/archived
                                            /js/processes/categories/index.js    266 KiB             /js/processes/categories/index  [emitted]  /js/processes/categories/index
                                                        /js/processes/edit.js   96.3 KiB                         /js/processes/edit  [emitted]  /js/processes/edit
                                 /js/processes/environment-variables/index.js    257 KiB  /js/processes/environment-variables/index  [emitted]  /js/processes/environment-variables/index
                                                       /js/processes/index.js    356 KiB                        /js/processes/index  [emitted]  /js/processes/index
                                               /js/processes/modeler/index.js   11.8 MiB                /js/processes/modeler/index  [emitted]  /js/processes/modeler/index
                                         /js/processes/modeler/initialLoad.js   12.1 MiB          /js/processes/modeler/initialLoad  [emitted]  /js/processes/modeler/initialLoad
                                         /js/processes/screen-builder/main.js   10.6 MiB          /js/processes/screen-builder/main  [emitted]  /js/processes/screen-builder/main
                                  /js/processes/screen-builder/typeDisplay.js   10.2 MiB   /js/processes/screen-builder/typeDisplay  [emitted]  /js/processes/screen-builder/typeDisplay
                                     /js/processes/screen-builder/typeForm.js   10.3 MiB      /js/processes/screen-builder/typeForm  [emitted]  /js/processes/screen-builder/typeForm
                                                /js/processes/screens/edit.js    112 KiB                 /js/processes/screens/edit  [emitted]  /js/processes/screens/edit
                                               /js/processes/screens/index.js    353 KiB                /js/processes/screens/index  [emitted]  /js/processes/screens/index
                                                /js/processes/scripts/edit.js    114 KiB                 /js/processes/scripts/edit  [emitted]  /js/processes/scripts/edit
                                          /js/processes/scripts/editConfig.js    112 KiB           /js/processes/scripts/editConfig  [emitted]  /js/processes/scripts/editConfig
                                               /js/processes/scripts/index.js    351 KiB                /js/processes/scripts/index  [emitted]  /js/processes/scripts/index
                                                        /js/requests/index.js   1.07 MiB                         /js/requests/index  [emitted]  /js/requests/index
                                                      /js/requests/preview.js   10.2 MiB                       /js/requests/preview  [emitted]  /js/requests/preview
                                                         /js/requests/show.js   10.5 MiB                          /js/requests/show  [emitted]  /js/requests/show
                                                              /js/snap.svg.js    276 KiB                                             [emitted]
                                                           /js/tasks/index.js   1.07 MiB                            /js/tasks/index  [emitted]  /js/tasks/index
                                                            /js/tasks/show.js   10.3 MiB                             /js/tasks/show  [emitted]  /js/tasks/show
                                                               /js/timeout.js  796 bytes                                             [emitted]
                                                                /js/vendor.js   7.31 MiB                                 /js/vendor  [emitted]  /js/vendor
/vendor/monaco-editor/min/vs/base/browser/ui/codiconLabel/codicon/codicon.ttf   55.2 KiB                                             [emitted]
                       /vendor/monaco-editor/min/vs/base/worker/workerMain.js    166 KiB                                             [emitted]
                /vendor/monaco-editor/min/vs/basic-languages/csharp/csharp.js   4.81 KiB                                             [emitted]
                      /vendor/monaco-editor/min/vs/basic-languages/css/css.js   4.76 KiB                                             [emitted]
                    /vendor/monaco-editor/min/vs/basic-languages/java/java.js   3.28 KiB                                             [emitted]
        /vendor/monaco-editor/min/vs/basic-languages/javascript/javascript.js   6.32 KiB                                             [emitted]
                      /vendor/monaco-editor/min/vs/basic-languages/lua/lua.js   2.45 KiB                                             [emitted]
                      /vendor/monaco-editor/min/vs/basic-languages/php/php.js   8.21 KiB                                             [emitted]
                /vendor/monaco-editor/min/vs/basic-languages/python/python.js   3.55 KiB                                             [emitted]
                          /vendor/monaco-editor/min/vs/basic-languages/r/r.js   3.14 KiB                                             [emitted]
                          /vendor/monaco-editor/min/vs/editor/editor.main.css   88.9 KiB                                             [emitted]
                           /vendor/monaco-editor/min/vs/editor/editor.main.js   2.24 MiB                                             [emitted]
                       /vendor/monaco-editor/min/vs/editor/editor.main.nls.js   46.8 KiB                                             [emitted]
                                       /vendor/monaco-editor/min/vs/loader.js   29.5 KiB                                             [emitted]

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
7 │ @import '../../public/css/precompiled/bootstrap/bootstrap.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  /home/azureuser/processmaker/resources/sass/app.scss 7:9  root stylesheet
    at /home/azureuser/processmaker/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/azureuser/processmaker/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/azureuser/processmaker/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/azureuser/processmaker/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/azureuser/processmaker/node_modules/sass-loader/dist/index.js:73:7
    at Function.call$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:89862:16)
    at _render_closure1.call$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:79036:12)
    at _RootZone.runBinary$3$3 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:26612:18)
    at _FutureListener.handleError$1 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:25140:19)
    at _Future__propagateToListeners_handleError.call$0 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:25437:49)
    at Object._Future__propagateToListeners (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:4502:77)
    at _Future._completeError$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:25270:9)
    at _AsyncAwaitCompleter.completeError$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:24613:12)
    at Object._asyncRethrow (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:4251:17)
    at /home/azureuser/processmaker/node_modules/sass/sass.dart.js:13112:20
    at _wrapJsFunctionForAsync_closure.$protected (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:4276:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:24634:12)
    at _awaitOnObject_closure0.call$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:24626:25)
    at _RootZone.runBinary$3$3 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:26612:18)
    at _FutureListener.handleError$1 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:25140:19)
    at _Future__propagateToListeners_handleError.call$0 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:25437:49)
    at Object._Future__propagateToListeners (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:4502:77)
    at _Future._completeError$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:25270:9)
    at _AsyncAwaitCompleter.completeError$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:24613:12)
    at Object._asyncRethrow (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:4251:17)
    at /home/azureuser/processmaker/node_modules/sass/sass.dart.js:15754:20
    at _wrapJsFunctionForAsync_closure.$protected (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:4276:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:24634:12)
    at _awaitOnObject_closure0.call$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:24626:25)
    at _RootZone.runBinary$3$3 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:26612:18)
    at _FutureListener.handleError$1 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:25140:19)
    at _Future__propagateToListeners_handleError.call$0 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:25437:49)
    at Object._Future__propagateToListeners (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:4502:77)
    at _Future._completeError$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:25270:9)
    at _AsyncAwaitCompleter.completeError$2 (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:24613:12)
    at Object._asyncRethrow (/home/azureuser/processmaker/node_modules/sass/sass.dart.js:4251:17)
 @ ./resources/sass/app.scss

ERROR in ./resources/sass/app.scss (./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/app.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
7 │ @import '../../public/css/precompiled/bootstrap/bootstrap.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  /home/azureuser/processmaker/resources/sass/app.scss 7:9  root stylesheet
 @ ./resources/sass/app.scss 2:14-253
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @processmaker/processmaker@4.0.13 development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @processmaker/processmaker@4.0.13 development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-20T12_33_44_567Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @processmaker/processmaker@4.0.13 dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @processmaker/processmaker@4.0.13 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-20T12_33_45_424Z-debug.log`

**Comment by velkymx** [comment]
Please update to the latest release.
