### ISSUE TITLE
 Class "Facade\Ignition\LogRecorder\LogMessage" not found

### ISSUE THREAD

**Issue by eng-haider** [ProcessMaker/processmaker#4626]
Class "Facade\Ignition\LogRecorder\LogMessage" not found

**Comment by Hector-as** [comment]
I think I'm having the same problem, just for give a bit more information. Every time I navigate between pages the error is thrown, it doesn't block me but I would like to solve it.

`
[2023-04-12 11:26:17] production.ERROR: Class "Facade\Ignition\LogRecorder\LogMessage" not found {"userId":1,"exception":"[object] (Error(code: 0): Class \"Facade\\Ignition\\LogRecorder\\LogMessage\" not found at /processmaker/vendor/facade/ignition/src/LogRecorder/LogRecorder.php:39)
[stacktrace]
#0 /processmaker/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(404): Facade\\Ignition\\LogRecorder\\LogRecorder->record()
#1 /processmaker/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#2 /processmaker/vendor/laravel/framework/src/Illuminate/Log/Logger.php(245): Illuminate\\Events\\Dispatcher->dispatch()
#3 /processmaker/vendor/laravel/framework/src/Illuminate/Log/Logger.php(186): Illuminate\\Log\\Logger->fireLogEvent()
#4 /processmaker/vendor/laravel/framework/src/Illuminate/Log/Logger.php(106): Illuminate\\Log\\Logger->writeLog()
#5 /processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(105): Illuminate\\Log\\Logger->warning()
#6 /processmaker/vendor/laravel/framework/src/Illuminate/Support/helpers.php(377): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#7 /processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): with()
#8 /processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(71): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleDeprecation()
#9 /processmaker/vendor/composer/ClassLoader.php(480): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#10 /processmaker/vendor/composer/ClassLoader.php(480): include('...')
#11 /processmaker/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()
#12 /processmaker/vendor/facade/ignition/src/LogRecorder/LogRecorder.php(39): Composer\\Autoload\\ClassLoader->loadClass()
#13 /processmaker/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(404): Facade\\Ignition\\LogRecorder\\LogRecorder->record()
#14 /processmaker/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#15 /processmaker/vendor/laravel/framework/src/Illuminate/Log/Logger.php(245): Illuminate\\Events\\Dispatcher->dispatch()
#16 /processmaker/vendor/laravel/framework/src/Illuminate/Log/Logger.php(186): Illuminate\\Log\\Logger->fireLogEvent()
#17 /processmaker/vendor/laravel/framework/src/Illuminate/Log/Logger.php(130): Illuminate\\Log\\Logger->writeLog()
#18 /processmaker/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(631): Illuminate\\Log\\Logger->info()
#19 /processmaker/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Log\\LogManager->info()
#20 /processmaker/ProcessMaker/Models/ProcessRequestToken.php(219): Illuminate\\Support\\Facades\\Facade::__callStatic()
#21 /processmaker/ProcessMaker/Http/Controllers/Api/NotificationController.php(437): ProcessMaker\\Models\\ProcessRequestToken->getNotifiables()
#22 /processmaker/ProcessMaker/Http/Controllers/Api/NotificationController.php(76): ProcessMaker\\Http\\Controllers\\Api\\NotificationController->notifyOverdueTasks()
#23 /processmaker/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): ProcessMaker\\Http\\Controllers\\Api\\NotificationController->index()
#24 /processmaker/ProcessMaker/Http/Controllers/Controller.php(36): Illuminate\\Routing\\Controller->callAction()
#25 /processmaker/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): ProcessMaker\\Http\\Controllers\\Controller->callAction()
#26 /processmaker/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#27 /processmaker/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#28 /processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#29 /processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#30 /processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#32 /processmaker/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#34 /processmaker/ProcessMaker/Http/Middleware/SetLocale.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): ProcessMaker\\Http\\Middleware\\SetLocale->handle()
#36 /processmaker/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#38 /processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#40 /processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#41 /processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#42 /processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#43 /processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#44 /processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#45 /processmaker/ProcessMaker/Http/Middleware/BrowserCache.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): ProcessMaker\\Http\\Middleware\\BrowserCache->handle()
#47 /processmaker/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#49 /processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#51 /processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#52 /processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#54 /processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#55 /processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#57 /processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#59 /processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#61 /processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#62 /processmaker/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#63 /processmaker/server.php(21): require_once('...')
#64 {main}
"} 
`
